### ISSUE TITLE
Hey Teacher O my Teacher! I think Login and Sign Up button's redirects logic (On the Home page) probably not correct 

### ISSUE THREAD

**Issue by akshatsaini-dev** [jamezmca/broodl#2]
I followed this project till the end!
and there's this thing that both the button's on Home page, will lead to same redirect of 
Login
You're one step away!

Email -
Password - 

Submit

Don't have an account? Sign up

rather, Sign Up button should lead to Register and Login to Login, separately.
Please look if the issue is correct and let me know

Good Vibes only!

**Comment by jamezmca** [comment]
Yes and no. 

The redirect works appropriately, as it takes the user to the dashboard which is authentication protected, and hence displays the login component. Signup and registration both exist within login component.

I made it as is because both buttons just need to take the user to a place where they can either login or register, as it's easy for them to swap between the two states. What you could do to refine it is add a query to the redirect for each that determines whether or not the login or the registration version is shown by default.

**Comment by akshatsaini-dev** [comment]
Thank you so much for the advice! I did it by creating and routing to different Sign In and Login pages for each button.

**Comment by jamezmca** [comment]
Sounds great! Just make sure you don't leave the dashboard unprotected for people who aren't authenticated!

**Comment by akshatsaini-dev** [comment]
Already had that in mind from your teachings! :)
